package com.lostandfound;

/**
 * Created by Mariachi on 05.11.2017.
 */

//this class will be used to store data in unified format
public class UnifiedDataStructure {

    private String nameOfItem;
    private int itemID; //this ID is generated by our programme
    private String cityOfFound;
    private String placeOfFound;
    private String commment;
    private String itemSourceID; //this ID is received specific site
    private String URLAddressOfSource;


}
