DROP SCHEMA `LOST_FOUND_APP`; 

CREATE SCHEMA  `LOST_FOUND_APP` ;

CREATE TABLE `LOST_FOUND_APP`.`LOST_ITEM` (
  `LOST_ITEM_ID` int(11) IDENTITY NOT NULL,
  `NAME_OF_ITEM` varchar(100) DEFAULT NULL,
  `CITY_OF_FOUND` varchar(45) DEFAULT NULL,
  `PLACE_OF_FOUND` varchar(100) DEFAULT NULL,
  `COMMENT` varchar(45) DEFAULT NULL,
  `ITEM_SOURCE_ID` varchar(45) DEFAULT NULL,
  `URL_ADDRESS_OF_SOURCE` varchar(100) DEFAULT NULL,
  `DATE_OF_FOUND` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`LOST_ITEM_ID`)
)DEFAULT CHARSET=utf8;