package com.lostandfoundapp.parsers.item;

import java.io.Serializable;

public class Item implements Serializable{

    private String nameOfItem;
    private int itemID; //this ID is generated by our programme
    private String cityOfFound;
    private String placeOfFound;
    private String comment;
    private String itemSourceID; //this ID is received specific site
    private String URLAddressOfSource;
    private String dateOfFinding;


    public Item(){
        nameOfItem = "";
        itemID = -1;
        cityOfFound = "";
        placeOfFound = "";
        comment = "";
        itemSourceID = "";
        URLAddressOfSource = "";
        dateOfFinding = "";
    }

    public Item(Item a){
        nameOfItem = a.getNameOfItem();
        itemID = a.getItemID();
        cityOfFound = a.getCityOfFound();
        placeOfFound = a.getPlaceOfFound();
        comment = a.getComment();
        itemSourceID = a.getItemSourceID();
        URLAddressOfSource = a.getURLAddressOfSource();
        dateOfFinding = a.getDateOfFinding();
    }

    public String getDateOfFinding() {
        return dateOfFinding;
    }

    public void setDateOfFinding(String dateOfFinding) {
        this.dateOfFinding = dateOfFinding;
    }

    public String getNameOfItem() {
        return nameOfItem;
    }

    public void setNameOfItem(String nameOfItem) {
        this.nameOfItem = nameOfItem;
    }

    public int getItemID() {
        return itemID;
    }

    public void setItemID(int itemID) {
        this.itemID = itemID;
    }

    public String getCityOfFound() {
        return cityOfFound;
    }

    public void setCityOfFound(String cityOfFound) {
        this.cityOfFound = cityOfFound;
    }

    public String getPlaceOfFound() {
        return placeOfFound;
    }

    public void setPlaceOfFound(String placeOfFound) {
        this.placeOfFound = placeOfFound;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String commment) {
        this.comment = commment;
    }

    public String getItemSourceID() {
        return itemSourceID;
    }

    public void setItemSourceID(String itemSourceID) {
        this.itemSourceID = itemSourceID;
    }

    public String getURLAddressOfSource() {
        return URLAddressOfSource;
    }

    public void setURLAddressOfSource(String URLAddressOfSource) {
        this.URLAddressOfSource = URLAddressOfSource;
    }

}